Changes started

diff --git a/src/site/resources/argo/review/argo-wf.yaml b/src/site/resources/argo/review/argo-wf.yaml
--- a/src/site/resources/argo/review/argo-wf.yaml
+++ b/src/site/resources/argo/review/argo-wf.yaml
@@ -15,20 +15,16 @@ spec:
     entrypoint: pipeline
     arguments:
         parameters:
-            -   name: repo-url
-                value: "git@bitbucket.org:example/example-app.git"
-            -   name: working-dir
-                value: "/var/opt/setmy.info/minikube"
-            -   name: repo-name
-                value: "example-app"
-            -   name: from-commit
-                value: "HEAD~1"
-            -   name: to-commit
-                value: "HEAD"
-            -   name: agent
-                value: "claude"
             -   name: uuid
                 value: "427ae6c8-2d17-4e1c-be75-2c43883cdf95"
+            -   name: working-dir
+                value: "example-app"
+            -   name: repo-list
+                value: '[{"url": "git@bitbucket.org:example/example-app.git", "branch": "master", "from": "HEAD~1", "to": "HEAD"}]'
+            -   name: main-project-folder
+                value: "example-app"
+            -   name: agent
+                value: "claude"
             -   name: mode
                 value: "review"
     templates:
@@ -36,15 +32,37 @@ spec:
             steps:
                 -   -   name: setup-dir
                         template: setup-dir
-                -   -   name: clone-git
-                        template: clone-git
+                -   -   name: setup-ssh
+                        template: setup-ssh
+                -   -   name: git-clone
+                        template: git-clone
+                        arguments:
+                            parameters:
+                                -   name: repo-url
+                                    value: "{{item.url}}"
+                                -   name: branch
+                                    value: "{{item.branch}}"
+                                -   name: from-commit
+                                    value: "{{item.from}}"
+                                -   name: to-commit
+                                    value: "{{item.to}}"
+                        withParam: "{{workflow.parameters.repo-list}}"
                 -   -   name: generate-diff
                         template: generate-diff
-                        when: "{{workflow.parameters.mode}} != code"
-                -   -   name: create-tasklist
-                        template: create-tasklist
-                -   -   name: run-agent
-                        template: run-agent
+                        arguments:
+                            parameters:
+                                -   name: repo-url
+                                    value: "{{item.url}}"
+                                -   name: from-commit
+                                    value: "{{item.from}}"
+                                -   name: to-commit
+                                    value: "{{item.to}}"
+                        withParam: "{{workflow.parameters.repo-list}}"
+                        when: "{{workflow.parameters.mode}} != code && $(basename {{item.url}} .git) == {{workflow.parameters.main-project-folder}}"
+#                -   -   name: create-tasklist
+#                        template: create-tasklist
+#                -   -   name: run-agent
+#                        template: run-agent
 
         -   name: setup-dir
             container:
@@ -57,11 +75,12 @@ spec:
                     - |
                         echo "Setting up directory: {{workflow.parameters.working-dir}}"
                         mkdir -p "{{workflow.parameters.working-dir}}/clones/{{workflow.parameters.uuid}}"
+                        mkdir -p "{{workflow.parameters.working-dir}}/.ssh"
                         ls -la "{{workflow.parameters.working-dir}}"
                         ls -la "{{workflow.parameters.working-dir}}/clones/{{workflow.parameters.uuid}}"
                         echo chown -R microservice:microservice "."
 
-        -   name: clone-git
+        -   name: setup-ssh
             container:
                 image: setmyinfo/setmy-info-rocky:latest
                 volumeMounts:
@@ -72,35 +91,43 @@ spec:
                 command: [ "/bin/sh", "-c" ]
                 args:
                     - |
+                        echo "Setting up SSH keys..."
+                        cp /host-ssh/id_ed25519 "{{workflow.parameters.working-dir}}/.ssh/id_ed25519"
+                        cp /host-ssh/known_hosts "{{workflow.parameters.working-dir}}/.ssh/known_hosts"
+                        chmod 600 "{{workflow.parameters.working-dir}}/.ssh/id_ed25519"
+                        chmod 644 "{{workflow.parameters.working-dir}}/.ssh/known_hosts"
+                        ls -la "{{workflow.parameters.working-dir}}/.ssh"
+
+        -   name: git-clone
+            inputs:
+                parameters:
+                    -   name: repo-url
+                    -   name: branch
+                    -   name: from-commit
+                    -   name: to-commit
+            container:
+                image: setmyinfo/setmy-info-rocky:latest
+                volumeMounts:
+                    -   name: shared-storage
+                        mountPath: "{{workflow.parameters.working-dir}}"
+                command: [ "/bin/sh", "-c" ]
+                args:
+                    - |
                         dnf update -y && \
                         dnf install -y \
                             git \
                         && dnf clean all
 
-                        ls -la /
-                        mkdir -p ~/.ssh
-                        cp /host-ssh/id_ed25519 ~/.ssh/id_ed25519
-                        cp /host-ssh/known_hosts ~/.ssh/known_hosts
-                        chmod 600 ~/.ssh/id_ed25519
-                        chmod 644 ~/.ssh/known_hosts
-
                         echo "Cloning to: {{workflow.parameters.working-dir}}/clones/{{workflow.parameters.uuid}}"
                         cd "{{workflow.parameters.working-dir}}/clones/{{workflow.parameters.uuid}}"
-                        git clone "{{workflow.parameters.repo-url}}"
-
-                        cd "{{workflow.parameters.repo-name}}"
-                        if [ -f "additional-clone.sh" ]; then
-                          echo "Executing additional-clone.sh..."
-                          chmod +x additional-clone.sh
-                          ./additional-clone.sh
-                        fi
-                        cd ../../..
-                env:
-                    -   name: CLONE_BASE_DIR
-                        value: "{{workflow.parameters.working-dir}}/clones/{{workflow.parameters.uuid}}"
-
+                        git clone -b "{{inputs.parameters.branch}}" "{{inputs.parameters.repo-url}}"
 
         -   name: generate-diff
+            inputs:
+                parameters:
+                    -   name: repo-url
+                    -   name: from-commit
+                    -   name: to-commit
             container:
                 image: setmyinfo/setmy-info-rocky:latest
                 volumeMounts:
@@ -116,13 +143,17 @@ spec:
                             git \
                         && dnf clean all
 
-                        echo "Generating diff for {{workflow.parameters.working-dir}}/clones/{{workflow.parameters.uuid}}"
-                        cd "{{workflow.parameters.working-dir}}/clones/{{workflow.parameters.uuid}}/{{workflow.parameters.repo-name}}"
-                        git diff "{{workflow.parameters.from-commit}}..{{workflow.parameters.to-commit}}" > "diff.patch" || { echo "Git diff failed"; exit 1; }
+                        REPO_NAME=$(basename "{{inputs.parameters.repo-url}}" .git)
+                        echo "Generating diff for {{workflow.parameters.working-dir}}/clones/{{workflow.parameters.uuid}} in $REPO_NAME"
+                        cd "{{workflow.parameters.working-dir}}/clones/{{workflow.parameters.uuid}}/$REPO_NAME"
+                        git diff "{{inputs.parameters.from-commit}}..{{inputs.parameters.to-commit}}" > "diff.patch" || { echo "Git diff failed"; exit 1; }
                         cd ../../..
 
 
         -   name: create-tasklist
+            inputs:
+                parameters:
+                    -   name: repo-url
             container:
                 image: setmyinfo/setmy-info-rocky:latest
                 volumeMounts:
@@ -135,15 +166,19 @@ spec:
                         echo "Installing gettext..."
                         dnf install -y gettext
 
-                        cd "{{workflow.parameters.working-dir}}/clones/{{workflow.parameters.uuid}}/{{workflow.parameters.repo-name}}"
+                        REPO_NAME=$(basename "{{inputs.parameters.repo-url}}" .git)
+                        cd "{{workflow.parameters.working-dir}}/clones/{{workflow.parameters.uuid}}/$REPO_NAME"
                         echo "Building tasklist..."
-                        cp -r "{{workflow.parameters.working-dir}}/{{workflow.parameters.repo-name}}/." .
+                        cp -r "{{workflow.parameters.working-dir}}/$REPO_NAME/." .
                         runuser -u microservice -- smi-build-tasklist
                         ls -la TASKLIST.md
                         cd ../../..
 
 
         -   name: run-agent
+            inputs:
+                parameters:
+                    -   name: repo-url
             container:
                 image: setmyinfo/setmy-info-rocky:latest
                 volumeMounts:
@@ -158,7 +193,8 @@ spec:
                             ca-certificates \
                         && dnf clean all
 
-                        cd "{{workflow.parameters.working-dir}}/clones/{{workflow.parameters.uuid}}/{{workflow.parameters.repo-name}}"
+                        REPO_NAME=$(basename "{{inputs.parameters.repo-url}}" .git)
+                        cd "{{workflow.parameters.working-dir}}/clones/{{workflow.parameters.uuid}}/$REPO_NAME"
                         if [ ! -f "agent.sh" ]; then
                           echo "Creating agent.sh..."
                           cat << 'EOF' > agent.sh
